version: '3.8'

services:
    auth:
        build:
            context: ./auth
            dockerfile: Dockerfile.dev
        ports:
            - '5000:5000'
        environment:
            - PORT=5000
            - API_VERSION=v1
            - MONGO_URI=mongodb://db:27017
            - JWT_KEY=jwttestkey12345
            - COOKIE_KEY=cookietestkey12345
        volumes:
            - './auth/:/node/app'
        depends_on:
            - db
    db:
        image: mongo
        logging:
            driver: none
        volumes:
            - 'progress_tracker_mongo_auth_service:/data/db'
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        stdin_open: true
        tty: true
        ports:
            - '3000:3000'
        volumes:
            - './client:/react/app'
        depends_on:
            - auth

volumes:
    progress_tracker_mongo_auth_service:
