version: "3.8"

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - API_VERSION=v1
      - MONGO_URI=mongodb://db:27017
    volumes:
      - "./auth/:/node/app"
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - "progress_tracker_mongo_auth_service:/data/db"

volumes:
  progress_tracker_mongo_auth_service:
