version: "3.8"

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - API_VERSION=v1
    volumes:
      - "./auth/:/node/app"
