export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const SET_FORM_MESSAGE = 'SET_FORM_MESSAGE';

export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECT = 'FETCH_PROJECT';
export const FETCH_PROJECTS_SUMMARY = 'FETCH_PROJECTS_SUMMARY';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';

export const FETCH_PROJECT_ITEMS = 'FETCH_PROJECT_ITEMS';
export const FETCH_PROJECT_ITEM = 'FETCH_PROJECT_ITEM';
export const CREATE_PROJECT_ITEM = 'CREATE_PROJECT_ITEM';
export const UPDATE_PROJECT_ITEM = 'UPDATE_PROJECT_ITEM';
export const DELETE_PROJECT_ITEM = 'DELETE_PROJECT_ITEM';
